"""Generate Harbor tasks from frozen FLBench instance manifests.

One task per (instance, config), as two compose services:

  * `main` runs the agent in `faultloc-agent:v1` and holds no ARVO content of
    its own -- no source, no PoC, no reproducer;
  * `poc` runs the digest-pinned `n132/arvo:<id>-vul`, stages the source onto a
    shared tmpfs volume, and serves the reproducer over four fixed HTTP
    endpoints.

Withholding is therefore structural: a config's resources are absent from the
agent's container unless staging puts them there, which is what makes the
ablations enforceable. The verifier shares the agent's container -- the scorer
is stdlib-only and that image already ships python3 -- and Harbor uploads
`tests/` only at verify time, so the ground truth never coexists with a live
agent.

See doc/migration-parity-plan.md for the design and the parity gate.
"""

import json
import shutil
from pathlib import Path

from . import manifest as manifest_mod
from .scorer import parse_diff

_TEMPLATE_DIR = Path(__file__).resolve().parent
_REPO_ROOT = Path(__file__).resolve().parents[2]

# Container the agent runs in; override with --agent-image. Pin it by digest before
# any calibration or main experiment -- a mutable tag lets the harness drift between runs.
DEFAULT_AGENT_IMAGE = "faultloc-agent:v1"

# Model API endpoints reachable during agent.run(). The environment baseline is
# no-network, so nothing else is: the reference relied on command-level denylists
# its own README calls bypassable, which let an agent fetch the upstream fix.
# `poc` is the sidecar's compose hostname: run_poc.sh must still reach it while the
# agent is policed. The rest are the model endpoints the supported agents dial --
# api.openai.com for codex on an API key, chatgpt.com and auth.openai.com for codex
# on a ChatGPT subscription (auth.json), api.anthropic.com for claude-code. A host
# missing here fails at the network layer mid-run, so the default covers every
# provider the harness ships with. Self-hosted endpoints need --allowed-hosts.
DEFAULT_ALLOWED_HOSTS = (
    "poc",
    "api.anthropic.com",
    "api.openai.com",
    "chatgpt.com",
    "auth.openai.com",
)

POC_TIMEOUT_SEC = 120

# Written once staging finishes; the main service's healthcheck gates on it.
STAGED_SENTINEL = "/workspace/.staged"

# Which resources each benchmark config exposes, mirroring the reference
# entrypoint (src/flbench/eval/image/entrypoint.sh).
CONFIGS = {
    "main": {"source": True, "poc_file": True, "report": True, "run_tool": True},
    "ablation1": {"source": True, "poc_file": True, "report": False, "run_tool": False},
    "ablation2": {"source": True, "poc_file": False, "report": True, "run_tool": True},
    "sanity": {"source": False, "poc_file": True, "report": True, "run_tool": True},
}

# Only `main` is generated by default. The ablation configs withhold resources
# that remain reachable in the ARVO image (/src/<project>, /tmp/poc, /out, arvo),
# so they cannot be enforced here yet -- ablation2 in particular needs the PoC
# runnable but not readable, which one container cannot express. Opt in with
# --configs once enforcement lands; see doc/migration-parity-plan.md.
DEFAULT_CONFIGS = tuple(CONFIGS)

_RUN_POC = f"""#!/bin/sh
# Run the proof-of-concept crash reproducer.
# Exit 0 means the PoC did NOT crash; non-zero means it still crashes.
timeout {POC_TIMEOUT_SEC} arvo 2>&1
"""


def _staging_command(caps: dict) -> str:
    """Shell run as the agent container's command, before the agent starts.

    Withholding is structural here: the agent image contains no source, no PoC
    and no reproducer, so a resource is absent unless this script fetches it.
    Source arrives on the shared volume only when the `poc` sidecar stages it.
    """
    steps = [
        "set -eu",
        "mkdir -p /workspace /logs/artifacts",
        # The reference does this before handing over (entrypoint.sh:211); the tree
        # is staged by another container, so git would otherwise refuse it.
        "git config --global --add safe.directory '*'",
    ]
    if caps["poc_file"]:
        steps.append("curl -sf http://poc:8080/poc-file -o /workspace/poc")
    if not caps["run_tool"]:
        # Belt and braces: the sidecar also refuses /poc for this config.
        steps.append("rm -f /usr/local/bin/run_poc.sh")
    # Signal completion last: `docker compose up --wait` returns when the
    # container is *running*, not when this script finishes.
    steps.append(f"touch {STAGED_SENTINEL}")
    steps.append("exec sleep infinity")
    return "\n".join(steps)


def _instruction(manifest: dict, caps: dict) -> str:
    """Render the agent-facing prompt.

    Same template and section logic as the reference, except the sanitizer
    report is the one captured at freeze time rather than produced by running
    the PoC during task setup.
    """
    template = (_TEMPLATE_DIR / "prompt.md").read_text()

    resources = []
    if caps["source"]:
        resources.append("- The **vulnerable source code** at `/workspace/src`")
    if caps["poc_file"]:
        resources.append(
            "- A **PoC input binary** at `/workspace/poc` that you may inspect"
            + ("" if caps["run_tool"] else " as a file")
        )
    if caps["report"]:
        resources.append("- A **pre-run sanitizer report** (see below)")
    else:
        resources.append("- **Vulnerability metadata** (see below)")
    if caps["run_tool"]:
        resources.append("- `run_poc.sh` to re-execute the PoC and get a fresh sanitizer report")

    source_section = (
        "## Source Code\n\n"
        "The vulnerable source code is at `/workspace/src`. Explore it to understand "
        "the codebase."
        if caps["source"]
        else ""
    )

    metadata = (
        "**Vulnerability metadata:**\n"
        f"- Crash type: {manifest['crash_type'] or 'unknown'}\n"
        f"- Sanitizer: {manifest['sanitizer'] or 'unknown'}\n"
        f"- Fuzz target: {manifest['fuzz_target'] or 'unknown'}"
    )
    if caps["poc_file"]:
        poc_section = (
            "## Proof-of-Concept Input\n\n"
            "A fuzzer input (PoC) that triggers the vulnerability is available at "
            "`/workspace/poc`.\nYou may inspect it as a binary file to understand what "
            f"input patterns exercise the bug."
            + (f"\n\n{metadata}" if caps["report"] else "")
        )
    else:
        poc_section = ""

    if caps["report"]:
        rerun = (
            "\nYou can re-run it at any time using `run_poc.sh` to get a fresh report."
            if caps["run_tool"]
            else ""
        )
        sanitizer_section = (
            "## Sanitizer Report\n\n"
            "The following report was produced by running the PoC against the vulnerable "
            f"binary.{rerun}\n\n```\n{manifest['crash_output']}\n```"
        )
    else:
        sanitizer_section = f"## Vulnerability Metadata\n\n{metadata}"

    tools_section = (
        "- `run_poc.sh` — execute the PoC against the instrumented binary and capture "
        "a fresh sanitizer report"
        if caps["run_tool"]
        else "(none)"
    )

    text = (
        template.replace("{{INSTRUCTIONS}}", "\n".join(resources))
        .replace("{{SOURCE_SECTION}}", source_section)
        .replace("{{POC_SECTION}}", poc_section)
        .replace("{{SANITIZER_SECTION}}", sanitizer_section)
        .replace("{{DEDICATED_TOOLS_SECTION}}", tools_section)
    )
    if not caps["source"]:
        text += (
            "\n> **Important:** No source code is available in this mode. You must reason "
            "solely from\n> the sanitizer report and PoC. Do **not** attempt to fetch source "
            "code or documentation\n> from the internet.\n"
        )
    if not caps["run_tool"]:
        text += (
            "\n> **Note:** Try your best to identify the root cause. If after thorough "
            "investigation you cannot find any suspicious location, write an empty "
            "prediction (`[]`) and exit.\n"
        )
    return "\n".join(line.rstrip() for line in text.splitlines()) + "\n"


def _oracle_spans(gt_diff: str) -> list[dict]:
    """Exact ground-truth spans, used only by solution/solve.sh."""
    spans = []
    for hunk in parse_diff(gt_diff):
        for line in sorted(hunk.lines):
            spans.append({"file": hunk.file, "line_start": line, "line_end": line + 1})
    return spans


class FLBenchAdapter:
    def __init__(
        self,
        output_dir: Path,
        limit: int | None = None,
        overwrite: bool = False,
        task_ids: list[str] | None = None,
        manifest_dir: Path | None = None,
        configs: list[str] | None = None,
        agent_image: str = DEFAULT_AGENT_IMAGE,
        allowed_hosts: list[str] | None = None,
        org: str = "flbench",
        **kwargs,
    ):
        self.output_dir = Path(output_dir)
        self.limit = limit
        self.overwrite = overwrite
        self.task_ids = task_ids
        self.manifest_dir = Path(manifest_dir or Path(__file__).resolve().parents[2] / "manifests")
        self.configs = configs or list(DEFAULT_CONFIGS)
        self.agent_image = agent_image
        self.allowed_hosts = list(allowed_hosts or DEFAULT_ALLOWED_HOSTS)
        self.org = org

        unknown = set(self.configs) - set(CONFIGS)
        if unknown:
            raise ValueError(f"unknown config(s): {sorted(unknown)}")

    def _manifests(self) -> list[dict]:
        paths = sorted(self.manifest_dir.glob("*.json"))
        if self.task_ids:
            wanted = {str(t) for t in self.task_ids}
            paths = [p for p in paths if p.stem in wanted]
            missing = wanted - {p.stem for p in paths}
            if missing:
                raise FileNotFoundError(
                    f"no manifest in {self.manifest_dir} for: {sorted(missing)}. "
                    f"Freeze it first with `python -m faultloc_adapter.freeze`."
                )
        return [manifest_mod.load(p) for p in paths]

    def run(self) -> None:
        manifests = self._manifests()
        if not manifests:
            raise FileNotFoundError(f"no manifests found in {self.manifest_dir}")
        written = 0
        for manifest in manifests:
            for config in self.configs:
                # --limit counts tasks, matching its documented meaning; one
                # manifest fans out to one task per requested config.
                if self.limit is not None and written >= self.limit:
                    return
                if self._write_task(manifest, config):
                    written += 1

    def _write_task(self, manifest: dict, config: str) -> bool:
        caps = CONFIGS[config]
        task_id = f"faultloc__{manifest['local_id']}-{config}"
        task_dir = self.output_dir / task_id
        if task_dir.exists():
            if not self.overwrite:
                print(f"skip {task_id} (exists; use --overwrite)")
                return False
            shutil.rmtree(task_dir)

        for sub in ("environment", "solution", "tests/scorer"):
            (task_dir / sub).mkdir(parents=True, exist_ok=True)

        (task_dir / "task.toml").write_text(self._task_toml(manifest, task_id, caps))
        (task_dir / "instruction.md").write_text(_instruction(manifest, caps))
        (task_dir / "environment" / "docker-compose.yaml").write_text(
            self._compose(manifest, caps, config)
        )

        self._write_solution(task_dir, manifest)
        self._write_tests(task_dir, manifest)
        print(f"wrote {task_dir}")
        return True

    def _task_toml(self, manifest: dict, task_id: str, caps: dict) -> str:
        hosts = ", ".join(f'"{h}"' for h in self.allowed_hosts)
        workdir = "/workspace/src" if caps["source"] else "/tmp"
        return f"""version = "1.0"

[task]
name = "{self.org}/{task_id}"
description = "Root-cause localization for {manifest['project']}: {manifest['crash_type']}"
authors = []
keywords = ["fault-localization", "security", "oss-fuzz", "arvo"]

[metadata]
difficulty = "hard"
category = "debugging"
local_id = {manifest['local_id']}
project = "{manifest['project']}"
sanitizer = "{manifest['sanitizer']}"

[agent]
timeout_sec = 1800.0
# Applies during agent.run() only, so the model API is reachable while the
# upstream repository, the OSS-Fuzz issue tracker, and the fix commit are not.
network_mode = "allowlist"
allowed_hosts = [{hosts}]

[verifier]
timeout_sec = 300.0
network_mode = "no-network"

[environment]
docker_image = "{self.agent_image}"
# The reference cds into the discovered git root before launching the agent
# (FLBench entrypoint.sh:203-211); sanity starts from /tmp with no source. Without
# this the agent inherits `/`, which changes repository discovery and search.
workdir = "{workdir}"
# Baseline is public because staging must reach the PoC sidecar before any agent
# exists; `[agent]` below is what policies the run itself. Harbor applies phase
# policy during agent.run() but not during environment start or agent.setup().
network_mode = "public"
build_timeout_sec = 1800.0
cpus = 2
memory_mb = 4096
"""

    def _compose(self, manifest: dict, caps: dict, config: str) -> str:
        # Compose interpolates ${...} in the YAML before the shell ever sees it,
        # so a bare $ in the staging script silently becomes an empty string.
        staging = _staging_command(caps).replace("$", "$$")
        indented = "\n".join("        " + line for line in staging.splitlines())
        arvo = manifest_mod.pinned_image(manifest)
        project = manifest["project"]
        server = "\n".join(
            "        " + line
            for line in (_REPO_ROOT / "sidecar" / "server.py").read_text().splitlines()
        )

        # sanity withholds the source by never populating the shared volume, so
        # the agent container -- which has no /src of its own -- genuinely has none.
        if caps["source"]:
            source_stage = "\n".join(
                "        " + line
                for line in (
                    f"cp -a /src/{project}/. /shared/",
                    "git -C /shared clean -fdx >/dev/null 2>&1 || true",
                )
            )
        else:
            # sanity: leave the volume empty; the agent image has no source of its own.
            source_stage = "        true"

        return f"""# Split design, mirroring FLBench's eval job: the agent runs in `main`, which
# contains no source, PoC or reproducer of its own, and the ARVO image is confined
# to the `poc` sidecar. Withholding a resource is therefore structural -- the agent
# cannot reach what was never put in its container -- which is what makes the
# ablation configs enforceable.
services:
  main:
    # tini as PID 1 forwards SIGTERM; without it the staging shell's `exec`ed
    # process ignores it and docker waits out the full 10s grace period on every
    # teardown (measured: 21s -> 1s for the stack).
    init: true
    volumes:
      - "src:/workspace/src"
    # Gates readiness on the sentinel staging writes last. `up --wait` otherwise
    # returns as soon as /bin/sh starts, letting the agent begin before
    # /workspace/poc exists.
    healthcheck:
      test: ["CMD", "test", "-f", "{STAGED_SENTINEL}"]
      interval: 2s
      timeout: 5s
      retries: 300
      start_period: 3s
    depends_on:
      poc:
        condition: service_healthy
    command:
      - /bin/sh
      - -c
      - |
{indented}

  # Holds /out, /tmp/poc and the reproducer, and stages the source onto the shared
  # volume. The copy lives here rather than in a one-shot service because the volume
  # is tmpfs: it exists only while a container has it mounted, and this sidecar is up
  # for the whole trial. The mount point is an empty path, never /src/<project>, so
  # Docker cannot prepopulate the volume from the image behind the config's back.
  # The agent never sees this filesystem; it reaches the PoC only over HTTP.
  poc:
    init: true
    # The server disables ASLR so MSan's fixed shadow ranges cannot collide with a
    # randomly placed mapping (see sidecar/server.py:_disable_aslr). Docker's default
    # seccomp profile denies the personality syscall with EPERM, so the call is a
    # no-op without this. Scoped to the sidecar; the agent container keeps the
    # default profile.
    security_opt:
      - seccomp=unconfined
    environment:
      EVAL_CONFIG: "{config}"
      TIMEOUT: "{POC_TIMEOUT_SEC}"
    image: {arvo}
    networks: [default]
    volumes:
      - "src:/shared"
    command:
      - /bin/sh
      - -c
      - |
        set -eu
{source_stage}
        cat > /tmp/server.py <<'SERVER_EOF'
{server}
        SERVER_EOF
        exec python3 /tmp/server.py
    healthcheck:
      test: ["CMD", "python3", "-c",
             "import urllib.request;urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 2s
      timeout: 5s
      retries: 150
      start_period: 3s

volumes:
  # tmpfs-backed so the staged source lives in RAM, not on disk. Harbor's
  # `delete: false` teardown runs a plain `docker compose down`, which keeps named
  # volumes -- with a disk-backed volume every trial would leak a full source tree
  # (measured: ~120MB each, unbounded across trials). Here teardown unmounts the
  # tmpfs and the memory is released; only an empty volume object remains. `size`
  # is a ceiling, not an allocation, so it costs nothing until written.
  src:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4g
"""

    def _write_solution(self, task_dir: Path, manifest: dict) -> None:
        spans = json.dumps(_oracle_spans(manifest["gt_diff"]), indent=2)
        solve = task_dir / "solution" / "solve.sh"
        solve.write_text(
            f"""#!/bin/bash
# Oracle: emit the ground-truth spans. Never shipped to the agent.
set -eu
mkdir -p /logs/artifacts
cat > /logs/artifacts/prediction.json <<'JSON'
{spans}
JSON
echo "Oracle prediction for {manifest['local_id']}." > /logs/artifacts/summary.txt
cat /logs/artifacts/prediction.json
"""
        )
        solve.chmod(0o755)

    def _write_tests(self, task_dir: Path, manifest: dict) -> None:
        tests = task_dir / "tests"
        (tests / "gt.diff").write_text(manifest["gt_diff"])
        for name in ("__init__.py", "types.py", "ground_truth.py", "metrics.py"):
            shutil.copy(_TEMPLATE_DIR / "scorer" / name, tests / "scorer" / name)
        shutil.copy(_TEMPLATE_DIR / "score.py", tests / "score.py")
        test_sh = tests / "test.sh"
        # Start from a clean slate: the verifier shares the agent's container, so
        # /logs/verifier may already hold something. A scorer crash deliberately
        # leaves no reward file -- Harbor then errors the trial, keeping the
        # infrastructure failure separate from a genuine agent score, as the plan
        # requires. Malformed agent output is already scored by score.py itself.
        test_sh.write_text(
            "#!/bin/bash\n"
            "set -u\n"
            "mkdir -p /logs/verifier\n"
            "rm -f /logs/verifier/reward.json /logs/verifier/reward.txt\n"
            "python3 /tests/score.py \\\n"
            "  --prediction /logs/artifacts/prediction.json \\\n"
            "  --ground-truth /tests/gt.diff \\\n"
            "  --out /logs/verifier/reward.json\n"
            "cat /logs/verifier/reward.json\n"
        )
        test_sh.chmod(0o755)
